name: Build Extension

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create extension directory
      run: mkdir -p build
    
    - name: Copy extension files
      run: |
        cp -r extension/* build/
        # Remove any development or mock files
        rm -rf build/mocks
        rm -f build/*.jpg
        rm -f build/*.webp
        rm -f build/PRIVACY_POLICY.md
        rm -f build/README.md
        rm -f build/icons/generate-icons.html
    
    - name: Create zip file
      run: |
        cd build
        zip -r ../kapture-extension.zip .
        cd ..
    
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: kapture-extension-${{ github.sha }}
        path: kapture-extension.zip
        retention-days: 30
    
    - name: Upload extension artifact (latest)
      uses: actions/upload-artifact@v4
      with:
        name: kapture-extension-latest
        path: kapture-extension.zip
        retention-days: 7